# Generated by Django 2.2.6 on 2019-10-24 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='like',
            new_name='like_users',
        ),
    ]
